import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            <nav>
                <ul>
                    <li>one</li>
                    <li>two</li>
                </ul>
            </nav>
            <main>
                {children}
            </main>
        </section>
    );
}
